services:
  teceo-challenge-postgres:
    container_name: teceo-challenge-postgres
    hostname: teceo-challenge-postgres
    image: postgres:17.5-alpine
    shm_size: 1g
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${POSGRESDB_VOLUME_PATH}/.pg_data_teceo:/var/lib/postgresql/data
    networks:
      - teceo-challenge

  teceo-challenge-postgres-gui:
    image: dpage/pgadmin4:8.2
    container_name: teceo-challenge-postgres-gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
    volumes:
      - pg_data_teceo:/var/lib/pgadmin
    networks:
      - teceo-challenge
      

networks:
  teceo-challenge:

volumes:
  pg_data_teceo: